package com.github.bumblebee202111.doubean.coroutines

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine

/**
 * https://github.com/android/nowinandroid/commit/97dfe95d912e736e59ddb72c24a807b856f7eac3#diff-8285d328e41d5a916d5f3a88e45c02d5831f5c4d0a6af5c916d1f778c081c586L108
 */
/**
 * Returns a [Flow] whose values are generated by [transform] function that process the most
 * recently emitted values by each flow.
 */
fun <T1, T2, T3, T4, T5, T6, R> combine(
    flow: Flow<T1>,
    flow2: Flow<T2>,
    flow3: Flow<T3>,
    flow4: Flow<T4>,
    flow5: Flow<T5>,
    flow6: Flow<T6>,
    transform: suspend (T1, T2, T3, T4, T5, T6) -> R,
): Flow<R> = combine(
    combine(flow, flow2, flow3, ::Triple),
    combine(flow4, flow5, flow6, ::Triple),
) { t1, t2 ->
    transform(
        t1.first,
        t1.second,
        t1.third,
        t2.first,
        t2.second,
        t2.third,
    )
}

