package com.github.bumblebee202111.doubean.model.common

enum class FeedItemLayout {
    LAYOUT_STATUS,
    LAYOUT_DEFAULT_CONTENT_RECTANGLE,
    LAYOUT_ALBUM,
    LAYOUT_FOLD_PHOTO,
    LAYOUT_AD_VIDEO,
    LAYOUT_AD_ONE_LARGE_IMAGE,
    LAYOUT_RECOMMEND_TOPICS,
    LAYOUT_VIDEO_DEFAULT,
    LAYOUT_ONE_LARGE_IMAGE,
    LAYOUT_SUBJECT_LAYOUT,
    LAYOUT_ALBUM_DEFAULT,
    LAYOUT_RECOMMEND_GROUPS_LAYOUT,
    LAYOUT_INTEREST_SUBJECTS,
    LAYOUT_PROFILE_COLLECTION_GROUPS,
    LAYOUT_PROFILE_COLLECTION_ALBUM,
    LAYOUT_TOPIC_CARD,
    LAYOUT_PODCAST_EPISODE,
    LAYOUT_AD_FOUR_IMAGES,
    UNKNOWN
}